### ISSUE TITLE
Anchor links naming scheme

### ISSUE THREAD

**Issue by agraul** [openSUSE/get-o-o#10]
Currently, all anchor links to the tabs all end with `-ports`. This means the installation (default) tab is called https://software.opensuse.org/distributions/leap#Installation-ports for Leap and https://software.opensuse.org/distributions/tumbleweed#Installation-ports for TW.

They are also capitalized while all other URLs are all-lowercase.

My suggestion is to drop the `-ports` part of those URLs and turn them all-lowercase to fit the rest of the URLs.

**Comment by hellcp** [comment]
Renamed to `_images`
