### ISSUE TITLE
Add Leap Micro to server distros

### ISSUE THREAD

**Issue by hellcp** [openSUSE/get-o-o#101]
Something like this, but with a different description, since I just copied the MicroOS one for mockup purposes:
![Screenshot from 2022-05-30 12-23-00](https://user-images.githubusercontent.com/30577011/170974007-12b78623-254c-498b-be4a-3b9060e185d6.png)

**Comment by lilfrogg** [comment]
Well, but one is **super stable**, so the other can still be stable. :-P

But no, I get it. I guess something like. Maybe just using "Rolling Release" and "Regular Release" as the taglines, or simply losing the taglines altogether could work then.

**Comment by lilfrogg** [comment]
Without taglines it could look something like this:
```
Tumbleweed
A traditional and highly customizable distribution for your servers.
Rolling release with the latest packages provided by the openSUSE Project.

Leap
A traditional and highly customizable distribution for your servers.
Regular release with the benefits of both enterprise-grade engineering and community-developed innovation.

MicroOS
Immutable base system designed to host single purpose container applications with automated administration & patching
Rolling release with the latest packages provided by the openSUSE Project.

Leap Micro
Immutable base system designed to host single purpose container applications with automated administration & patching
Regular release with the benefits of both enterprise-grade engineering and community-developed innovation.
```
Could also bring back the "For sysadmins...." part of the description then, but do those actually fit? Especially in case of tumbleweed-

**Comment by honyczek** [comment]
This needs some progress. I've realized there is a misleading description on [server](https://github.com/openSUSE/get-o-o/blob/main/server.html#L8) page "Four comfortably boring distributions, how it always should be" although there are only three distributions: Tumbleweed, Leap, MicroOS. Probably the inconsistency was introduced by removing Kubic distribution in PR #100 .
