### ISSUE TITLE
Compiling mpich 3.2.1 with ifort 18.03

### ISSUE THREAD

**Issue by giospud** [openSUSE/get-o-o#104]
Dear all
I am trying to ocmpile mpich2 3.2.1 with ifort and icc v 18.0.3 and I get this error:

make[3]: Entering directory '/opt/src/mpich-3.2.1/src/mpi/romio'
  CC       adio/common/heap-sort.lo
In file included from adio/common/heap-sort.c(12):
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/include/math.h(1230): error: identifier "_LIB_VERSION_TYPE" is undefined
  _LIBIMF_EXTERN_C _LIB_VERSIONIMF_TYPE _LIBIMF_PUBVAR _LIB_VERSIONIMF;
                   ^

Any hint?

**Comment by hellcp** [comment]
This is an issue tracker for the get.opensuse.org website, go to bugzilla.opensuse.org to report distribution bugs

**Comment by cboltz** [comment]
You'll need to log in with your openSUSE account (if you don't have one yet, create it on https://idp-portal.suse.com/univention/self-service/#page=createaccount )

If the bugzilla login fails or you can't create a bugreport after logging in in bugzilla, you can mail admin AT opensuse DOT org - but please include some more details than "doesn't work" ;-)

**Comment by giospud** [comment]
Hi cboltz
actually when I try to login I get the following message:

You are not authorized to perform this action.
Server error message:
Either username or password is incorrect or you are not allowed to use this service.

So it seems that I am not allowed to login

I will write directly to admin

Thanks
