### ISSUE TITLE
MicroOS download page doesn't show size of images

### ISSUE THREAD

**Issue by ivanvorstanenko** [openSUSE/get-o-o#118]
It applies to both main download page and "Alternative Downloads" page.

![изображение](https://user-images.githubusercontent.com/47495504/187719099-292043cb-9791-4c63-9006-915b6c5b5e34.png)
![изображение](https://user-images.githubusercontent.com/47495504/187719689-50f430cf-f10e-4554-adf3-41622673306b.png)

[Link](https://get.opensuse.org/microos/).

But, on other pages this problem don't exist.

**Comment by ivanvorstanenko** [comment]
Fixed!
Maybe, it will be good idea to add something like "NOT AVAILABLE" in the brackets, when links don't exist.

Anyway, thanks!

**Comment by hellcp** [comment]
It happens and disappears on its own, whenever the download server goes down and back up, so we really have little to no control over it

**Comment by ivanvorstanenko** [comment]
> It happens and disappears on its own, whenever the download server goes down and back up, so we really have little to no control over it

I needed to clarify : downloads were available. But the image size was not.
But, as I understand, it's also server side problem. Right?

**Comment by hellcp** [comment]
The website is only generated every hour, so it depends on the availability of the server the moment the rebuild happens
