### ISSUE TITLE
Link to the Leap Micro 5.3 in the Leap Micro 5.2 page open Leap 15.5

### ISSUE THREAD

**Issue by milachew** [openSUSE/get-o-o#121]
![изображение](https://user-images.githubusercontent.com/113530911/190196847-a0d63543-c13d-4c8d-8624-d40207f611df.png)

**Comment by hellcp** [comment]
Yeah, it should be a direct link most likely as well, shouldn't be too hard to fix that

**Comment by hellcp** [comment]
I did this commit, it will deploy in 15 or so minutes https://github.com/openSUSE/get-o-o/commit/90ca78b5479b913aabd09c7b020ba60cfa7e6b1b, let me know if it fixes the issue or if I broke something else :P

**Comment by milachew** [comment]
> I did this commit, it will deploy in 15 or so minutes [90ca78b](https://github.com/openSUSE/get-o-o/commit/90ca78b5479b913aabd09c7b020ba60cfa7e6b1b), let me know if it fixes the issue or if I broke something else :P

Yeap, it fixed!
This is the fastest bug fix I've ever seen :)

**Comment by hellcp** [comment]
And I even managed to eat dinner between the report and fixing of it
