### ISSUE TITLE
ppc64 big-endian images not shown on https://get.opensuse.org/tumbleweed/

### ISSUE THREAD

**Issue by tbazant** [openSUSE/get-o-o#125]
Can you please make the big-endian ISO images of openSUSE Tumbleweed visible on this download page? It is quite hard for users/testers to browse manually to https://download.opensuse.org/ports/ppc/tumbleweed/iso/openSUSE-Tumbleweed-DVD-ppc64-Current.iso - the original bug is at https://bugzilla.suse.com/show_bug.cgi?id=1203688

**Comment by hellcp** [comment]
We don't currently have Ports category for Tumbleweed or more recent Leaps, but you should be able to add something like https://github.com/openSUSE/get-o-o/blob/main/_data/152.yml#L140-L186 to the end of https://github.com/openSUSE/get-o-o/blob/main/_data/tumbleweed.yml.

**Comment by tbazant** [comment]
The 

> We don't currently have Ports category for Tumbleweed or more recent Leaps, but you should be able to add something like https://github.com/openSUSE/get-o-o/blob/main/_data/152.yml#L140-L186 to the end of https://github.com/openSUSE/get-o-o/blob/main/_data/tumbleweed.yml.

i've just created https://github.com/openSUSE/get-o-o/pull/127, please review, hope it works :-)
