### ISSUE TITLE
Leap Micro 5.2 page has broken link for 5.3

### ISSUE THREAD

**Issue by simonflood** [openSUSE/get-o-o#137]
Now Leap Micro 5.3 is available the 5.2 page displays a note at the top to say "Leap Micro 5.3 is now available for download" with a button to "Learn More". Unfortunately that button links to https://get.opensuse.org/leap%20micro (note the space) which is incorrect - the correct URL should be https://get.opensuse.org/leapmicro

If I could find where that's done I'd submit a PR myself.

**Comment by hellcp** [comment]
Found the issue and fixed it, it should be deployed in 15-25 minutes https://github.com/openSUSE/get-o-o/commit/a11e63a1c3c2424fa8390e1ecba3046685ad9b72

**Comment by simonflood** [comment]
Thanks!
