### ISSUE TITLE
Consider introducing release terminology (point and rolling release)

### ISSUE THREAD

**Issue by digitalethics** [openSUSE/get-o-o#17]
I didn't find specific release terminology anywhere on the new website to guide new users. Many end-users will make their choice dependent on whether a distribution is a **point release** or a **rolling release**. I am a firm believer that the rolling release model is the future, architecturally as well as philosophically, and I think it would be good for the openSUSE project to indicate this trend somewhere on the website.

**Comment by hellcp** [comment]
We already do though, headlines for Leap say it's a "Regular release" and Tumbleweed "Rolling release", please submit changes if you propose some more specific wording
