### ISSUE TITLE
Tumbleweed 404. Redirect Issues.

### ISSUE THREAD

**Issue by petcat30** [openSUSE/get-o-o#171]
Hey I wasn't sure where to report this. I was just trying to download Tumbleweed NET installer x86_64 and getting redirected to a 404 on this mirror.

openSUSE site has this link for Tumbleweed NET installer x86_64: 
https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Current.iso
    
Which redirects me to:
https://pkg.adfinis.com/opensuse/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20230917-Media.iso
    
But that file no longer exists on that mirror. The current "Snapshot" on that mirror is:
`openSUSE-Tumbleweed-NET-x86_64-Snapshot20230920-Media.iso`
    
It seems like the master server is still redirecting to an older snapshot, even though the mirror closest to me has updated to a new one. Since the snapshots get replaced the old one no longer exists on that mirror resulting in the 404.

**Comment by hellcp** [comment]
Issues like that are better reported to admin@opensuse.org than here
