### ISSUE TITLE
OpenSUSE-Tumbleweed-DVD-x86_64 Current Release (03-06-2024) Becomes Stuck at Hardware Detection

### ISSUE THREAD

**Issue by Chanabra** [openSUSE/get-o-o#189]
I have a Lenovo laptop with an intel i9-13900HX and Nvidia 4070 RTX GPU. 
In my bios I have the Graphics set to: Dynamic Graphics.

When attempting to install from USB, install becomes stuck at Hardware Detection, never advances. 

If I change my bios setting from Dynamic Graphics to Discrete Graphics, this issue does not happen and I can make a new install of Tumbleweed on my laptop. 

Then when I switch back to Dynamic Graphics after the install, I encounter a lot of problems. I am sure there is a way I can get around this, I do not have time at the moment though. 

Would love for this to be addressed so I can go forth with a new install. 

Apologies if I did not follow a correct formatting.

Thank you for your time

**Comment by Chanabra** [comment]
Seems there was maybe a slight change, the ISO filename was updated to a more recent date. 
I now get beyond the hardware detection with my standard Dynamic Graphic setting, however, there is a halt, indefinitely, at Probing USB Devices.

**Comment by hellcp** [comment]
This is not the place to report distribution bugs, check out https://bugzilla.opensuse.org instead
