### ISSUE TITLE
All downloads are displayed as "107 bytes" in size and links not working

### ISSUE THREAD

**Issue by IlgazC** [openSUSE/get-o-o#192]
I just noticed the downloads are "107 bytes" sized and the links not working.

Firefox (windows 11) stable  124.0.1
![Screenshot 2024-04-01 at 07-19-16 openSUSE Tumbleweed](https://github.com/openSUSE/get-o-o/assets/19528613/c1c18698-dc7b-429e-ba14-788200277f6c)

**Comment by IlgazC** [comment]
Additionally, when I check my local mirror http://mirror.verinomi.com/opensuse/tumbleweed/iso/, the "current stable" DVD images (ISO) are missing and yet their SHA256 etc. files are there.

**Comment by tacerus** [comment]
Hi, this was caused by an outage of the download system, see https://status.opensuse.org/.
The links pointing to https://download.opensuse.org are now operational and the sizes updated again.
