### ISSUE TITLE
Souldn't Leap base color be green

### ISSUE THREAD

**Issue by danchev** [openSUSE/get-o-o#20]
Everywhere else including [https://software.opensuse.org/](https://software.opensuse.org/distributions/leap), the base color for Leap is green and not orange.

**Comment by vinzv** [comment]
Even worse, it's two different colors on get-o-o:

![grafik](https://user-images.githubusercontent.com/74432/98105537-6f885500-1e98-11eb-92c9-e8594831ec94.png)
![grafik](https://user-images.githubusercontent.com/74432/98105564-77e09000-1e98-11eb-84f7-39c77daea631.png)

I don't get why we are killing our brand colors.

**Comment by hellcp** [comment]
That's the same colour, it's just overlaid on top of blue?

We are using yellow for Leap instead of green to make it not seem like the official distro. I described that during that long branding talk during oSC in 2019

**Comment by vinzv** [comment]
> That's the same colour, it's just overlaid on top of blue?

I'm not talking about color codes but of the visual impression. Of course it's orange half-transparent over blue - but it _looks_ brown.

> 
> We are using yellow for Leap instead of green to make it not seem like the official distro. I described that during that long branding talk during oSC in 2019

I get the use of accent colors to distinguish stuff. But why make the whole page orange like with a sledgehammer? Can't we be a bit more subtile like on Fedora does it on https://getfedora.org?

![grafik](https://user-images.githubusercontent.com/74432/98111345-bed28380-1ea0-11eb-801d-548a868ac301.png)

![grafik](https://user-images.githubusercontent.com/74432/98111365-c7c35500-1ea0-11eb-9fdb-cfb87b8b76c1.png)

**Comment by hellcp** [comment]
I don't see how Leap is any different compared to any other distro in this case tbh. I was planning on doing some other styling for the distros anyway, this is basically just lifted from software-o-o directly, with changed colour

**Comment by vinzv** [comment]
> I don't see how Leap is any different compared to any other distro in this case tbh. 

Right, the written above applies at least to Kubic and MicroOS as well. TW is a bit different as there the color is not that drastically different. But still.

> I was planning on doing some other styling for the distros anyway, this is basically just lifted from software-o-o directly, with changed colour

On software-o-o the colors were openSUSE-related. But on get-o-o they are completely different. That's why the whole thing got apparent only now.

**Comment by hellcp** [comment]
it's not like we have enough colours in the palette to cover all the distros anyway, so I'm sorry that we needed a new colour

**Comment by vinzv** [comment]
Then we should use the colors very carefully and furthermore not widen them by adding distortions through opacity.
