### ISSUE TITLE
Opens GitHub source Code link on the same page 

### ISSUE THREAD

**Issue by ansuman-shukla** [openSUSE/get-o-o#213]
![image](https://github.com/user-attachments/assets/ddf37dd7-8c82-4435-a3a1-9abbcc010530)

When we open the Source Code hyper link we get redirected to Github on same page , making it has to see the code ad Actual website side by side .

Source code hyperlink should open in a new tab.

**Comment by ansuman-shukla** [comment]
I would like to work on this

**Comment by tacerus** [comment]
Feel free to submit patches through pull requests.
