### ISSUE TITLE
get-o-o: Leap 15.3 appliance and live download links

### ISSUE THREAD

**Issue by lkocman** [openSUSE/get-o-o#34]
Leap 15.3 seems to be changing the way how appliance and live images are published.
The live images are currently broken.

This is a task to agree on the destination, and adjust get-o-o links so they work properly.

Adrian confirmed that we'd like to have only one publish dir for all :Images (not /Images - dvd5 etc). Which would be publishable (unfrozen) even after GA.

**Comment by Vogtinator** [comment]
Appliance (well, x86_64 JeOS) links are fine, only live isos are broken.

> Adrian confirmed that we'd like to have only one publish dir for all :Images (not /Images - dvd5 etc). Which would be publishable (unfrozen) even after GA.

That's been the case since 15.0, but it's always been `/live` for lives. Did anything change?

**Comment by lkocman** [comment]
Current workaround, which I'd like to avoid using long-term. I think pre-agreeing in the destination (be it appliances/iso or whatever else, and tweaking links. Would be the best. I'd also like to avoid having if version links in the page template. Any idea @hellcp? So far we've used live dir in 15.1 and 15.2. @adrianschroeter however recommends to publish all :Images to a single directory. (We'd have to ask autobuild to tweak rsyncd-internal.conf on pontifex in case we want to change it).
```
lkocman@pontifex2:/srv/ftp/pub/opensuse/distribution/leap/15.3> sudo ln -s appliances/iso live
lkocman@pontifex2:/srv/ftp/pub/opensuse/distribution/leap/15.3> pwd
/srv/ftp/pub/opensuse/distribution/leap/15.3

```

**Comment by hellcp** [comment]
Yeah, I think we need to have links tweaked in get-o-o, that seems like a better way to do this

**Comment by Vogtinator** [comment]
> Current workaround, which I'd like to avoid using long-term. I think pre-agreeing in the destination (be it appliances/iso or whatever else, and tweaking links. Would be the best.

AFAIK 15.2 was already set up in a way which followed Adrian's recommendation, as he did the setup himself IIRC. I have absolutely no idea how the publishing internally works anyway (and frankly, I don't want to know).

As long as there is finally some agreement on a location which we can keep for more than a single release I'm fine with it.

**Comment by lkocman** [comment]
Ack, my expectation is at least for two releases, I'm not really sure how will Leap look after 15.5 at this moment.
