### ISSUE TITLE
google-chrome blocks downloads from get-o-o

### ISSUE THREAD

**Issue by lkocman** [openSUSE/get-o-o#35]
Reproducer (tested on Tumbleweed, originally reported by users not running openSUSE): 

* install google-chrome from official repos
* Go to get.opensuse.org
* Leap -> Testing
* Click on x86_64 network image download 

Result: Nothing happens. Download is not initiated

Works on Chromium. Google-chrome has no problem directly downloading image from download.opensuse.org

**Comment by lkocman** [comment]
Workaround download image directly from e.g. http://download.opensuse.org/distribution/leap/15.3/

**Comment by lkocman** [comment]
@hellcp could you please have a look at the issue? This seems like a priority because of the beta testing effort.

**Comment by DanielNoga** [comment]
Originally reported by user using openSUSE :-) (but with Chrome downloaded directly from Google) 

Another workaround is click on download button via right mouse click and select download. Then Chrome allows to download with warning, that it is  dangerous.

**Comment by hellcp** [comment]
The error from chromium:
```
Mixed Content: The site at 'https://get.opensuse.org/' was loaded over a secure connection, but the file at 'http://ftp.vectranet.pl/opensuse/distribution/leap/15.3/iso/openSUSE-Leap-15.3-NET-x86_64-Build91.1-Media.iso' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```
We may have to talk with mirrorbrain guys, because I can't really force https on the redirects down the line

**Comment by hellcp** [comment]
For what it's worth, and I know it's not much, that would be very easy to fix with mirrormanager2, since you can actually request only getting https repos (using `protocol=https` in url) with it...

**Comment by hellcp** [comment]
https://progress.opensuse.org/issues/89578 for progress (haha) on the issue

The current decision seems to be to force get-o-o to redirect from https to http

**Comment by mess-maker** [comment]
hi just to add a little comment

if you click on https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Current.iso by the donwload button nothing happen
if you right click on the button with _save link as_ the redirect is resolved and point to : (in my case)
http://mirrors.gethosted.online/opensuse/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20210321-Media.iso
there the donwload is blocked with a security warning (you can enforce it and start the d/l)

now just replace **_http_** by **_https_** in the mirror url above and paste in the adress bar
bingo the download start immediately as expected.

tested also with this mirror with same results
http://ftp.halifax.rwth-aachen.de/opensuse/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20210321-Media.iso

clicking any mirror link in the mirror page https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-NET-x86_64-Snapshot20210321-Media.iso?mirrorlist
bring the security warning

tested on win 10 with google chrome 89.0.4389.90

**Comment by mess-maker** [comment]
nota

problem is not present on tumbleweed with chrome 90.0.4430.40 (beta)

**Comment by ykeyani** [comment]
So I noticed this issue has been around for over a month and will assume it will take time to make everything https.

I thought I would suggest adding some kind of instruction to new users as currently downloads fail silently and users will think the site is broken which would be a shame.

something like:
"to download files in chrome: right click and copy link address, paste in a new tab and hit enter"
in a big banner at the top.

**Comment by hellcp** [comment]
I added a note on this https://get.opensuse.org/tumbleweed/

**Comment by Zinc-OS** [comment]
That no longer works ;)
Chrome says that this download was blocked(with no keep button), when I clicked "save link as".
My solution,similar to what I used to download .debs from the debian website(Those don't work either, for similar reasons), is to copy the link address and paste it into the the search bar.

**Comment by hellcp** [comment]
This is fixed now
