### ISSUE TITLE
openSUSE Weblate bot doesn't trigger after new translations.

### ISSUE THREAD

**Issue by shenlebantongying** [openSUSE/get-o-o#36]
There are some translation mistakes on <https://get.opensuse.org/zh-CN/leap/>.

We have fixed them as shown on the [weblate's history](https://l10n.opensuse.org/changes/?project=get-o-o&component=main&lang=zh_CN). However, they are not merged to here. 

Also, the get-o-o are getting some alerts [0]. Translations in other languages' maybe get blocked too.

[0] https://l10n.opensuse.org/projects/get-o-o/main/#alerts

**Comment by hellcp** [comment]
Yup, sadly weblate was pulled back in time last week, so it got conflicting git repo on its side now

**Comment by shenlebantongying** [comment]
It is corrected now :+1: 

Thanks!
