### ISSUE TITLE
Startup guide link is broken

### ISSUE THREAD

**Issue by ddemaio** [openSUSE/get-o-o#51]
On https://get.opensuse.org/leap/, the startup guide link is broken. The script looks like to goes to https://doc.opensuse.org/documentation/leap/startup/single-html/book.opensuse.startup/index.html, but needs to go to https://doc.opensuse.org/documentation/leap/startup/html/book-startup/index.html
![Screenshot from 2021-06-14 16-05-48](https://user-images.githubusercontent.com/8996626/121905614-a249d400-cd2a-11eb-9d48-810f8508b2b0.png)

**Comment by aliya-rahmani** [comment]
@ddemaio I've made a PR for this, please review it!
