### ISSUE TITLE
metrics are broken

### ISSUE THREAD

**Issue by zoopster** [openSUSE/get-o-o#64]
https://metrics.opensuse.org/d/osrt_access/osrt-access?orgId=1 stopped showing data around  3 Sept 21. A number of other dashboard entries are also failing to load data for the most recent releases.
I'm not sure where that code resides in order to fix. Happy to help fix it as we're interested in reporting some interesting stats about opensuse downloads!!

**Comment by hellcp** [comment]
That's better to report to admin@opensuse.org instead of here

**Comment by ddemaio** [comment]
@zoopster @hellcp it would be fixed by the end of the week.
