### ISSUE TITLE
Mark releases as EOL

### ISSUE THREAD

**Issue by hellcp** [openSUSE/get-o-o#67]
Despite 15.1 and 15.2 being considered EOL by the project, that's not reflected in releases.yml, that should be corrected

**Comment by akshat5302** [comment]
Hey, @hellcp should I have to declare the state of releases (15.1 and 15.2) as EOL. If yes please assign this issue to me I will change them in the releases.yml file

**Comment by akshat5302** [comment]
I have merged a pull request with the main branch regarding this issue check that out @hellcp
