### ISSUE TITLE
Renaming JeOS to Minimal-VM

### ISSUE THREAD

**Issue by vmoutoussamy** [openSUSE/get-o-o#73]
Hi,

As JeOS images are now renamed Minimal-VM for 15.4 and SLES 15SP4 (https://jira.suse.com/browse/SLE-20354), we should replace JeOS in the download pages by Minimal-VM. 
Also the notice about ARM JeOS should be in a dedicated section, i.e out of the Minimal-VM section.
![jeos1](https://user-images.githubusercontent.com/3873925/157237258-246ba5e4-f576-4b23-9c8b-eb5224b62386.png)
![jeos2](https://user-images.githubusercontent.com/3873925/157237263-75dce6e7-0e03-487c-ab78-7d49e08dc219.png)

Regards,

**Comment by hellcp** [comment]
Feel free to adjust https://github.com/openSUSE/get-o-o/blob/main/_data/154.yml#L104-L149 and create new variables in https://github.com/openSUSE/get-o-o/blob/main/_data/locales/en.yml#L54-L55 so that everything is properly translated

**Comment by akshat5302** [comment]
Is this issue still open ??

**Comment by hellcp** [comment]
Nothing with regards to this issue was sent as a pull request, so I assume so

**Comment by vmoutoussamy** [comment]
Yes sorry, I will adjust the code, for now the website still use the former jeos images. So after this is fixed, I will update the page.

**Comment by dirkmueller** [comment]
That was merged, assuming it is fixed.
