### ISSUE TITLE
Unstable color for LeapMicro

### ISSUE THREAD

**Issue by lkocman** [openSUSE/get-o-o#78]
Hello,

I'm running the latest master locally and seems like I'm experiencing different background/header color for leapmicro_testing locally and also on production.

![localvsprod](https://user-images.githubusercontent.com/510119/161135024-607eb818-e382-4f8d-bba9-0cb32846907a.png)

**Comment by lkocman** [comment]
We want the orange, same on get.opensuse.org itself the color is also bit different.

Doug mentioned that he's getting orange color in one-browser while other browsers display gray.

**Comment by hellcp** [comment]
I suspect it's a cached css file, try a hard refresh

**Comment by hellcp** [comment]
I will close this now since it's not active
