### ISSUE TITLE
incorrect image size of Leap Micro 5.2 self-install rt image (169.0 B) 

### ISSUE THREAD

**Issue by lkocman** [openSUSE/get-o-o#89]
The Self-install RealTime Image (169.0 B) under https://get.opensuse.org/leapmicro/5.2/
has incorrectly calculated size, I did quickly submit a fix that was correcting the path (adding iso to appliances/iso) and I feel that it was initially calculated on invalid input or similar.

Could we please have the size recalculated?

Thank you

**Comment by lkocman** [comment]
@hellcp would this be something you could hava a look into?

**Comment by hellcp** [comment]
I did, and it seems some repos don't have that file yet, which is a problem for http redirects, because they don't go through mirrorcache, which verifies a file exists on the repo.
