### ISSUE TITLE
download page recommends downloadthemall! for Firefox- but it is not working any more since Firefox 57

### ISSUE THREAD

**Issue by BrigitteHuber** [openSUSE/get-o-o#9]
The download page https://software.opensuse.org/distributions/leap recommends using the Metalink with DownloadThemAll! for Firefox. DownloadThemAll! is not working any more in Firefox since version 57.

**Comment by vinzv** [comment]
DownloadThemAll! is back in development and works fine with newer Firefox versions.
Therefore close/fixed upstream.
