### ISSUE TITLE
[openSUSE Leap 15.4] missing rpm metadata of package pam

### ISSUE THREAD

**Issue by DonOtuseGH** [openSUSE/get-o-o#92]
Hello,

it seems that some relevant metadata of the package **pam** is missing:

```
ostest-lab-011:~ # rpm -qf /var/log/tallylog
file /var/log/tallylog is not owned by any package
ostest-lab-011:~ # zypper search --provides /var/log/tallylog
Loading repository data...
Reading installed packages...
No matching items found.
```

**/var/log/tallylog** seems to be the default logfile of pam module **pam_tally2**, i figured out...

Could you please have a look into this and fix the package accordingly?

Thanks a lot!

**Comment by hellcp** [comment]
This is not the place to report bugs about the distributions, go to https://bugs.opensuse.org and read how to do that
